version: "3"
services:
  nginx:
    build:
      context: ./service/nginx
    image: iuxt/dnmp_nginx
    container_name: nginx
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
      - ${NGINX_HTTPS_HOST_PORT}:443
    depends_on:
      - "php"
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:ro
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:ro
      - ${NGINX_SSL_DIR}:/etc/nginx/ssl/:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "${TZ}"
    restart: always
    networks:
      - default

  php:
    build:
      context: ./service/php-fpm_${PHP_VERSION}
    image: iuxt/dnmp_php-fpm:${PHP_VERSION}
    container_name: "php-fpm"
    expose:
      - 9000
    depends_on:
      - "mysql"
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:rw
      - type: bind
        source: ./service/php-fpm_${PHP_VERSION}/custom.ini
        target: "/usr/local/etc/php/conf.d/custom.ini"
    environment:
      TZ: "${TZ}"
    restart: always
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: "mysql"
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "${TZ}"
    restart: always
    networks:
      - default
