version: "3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:ro
      - ${NGINX_CONF_DIR}/conf.d:/etc/nginx/conf.d/:ro
      - ${NGINX_CONF_DIR}/ssl:/etc/nginx/ssl/:ro
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default

  php:
    build:
      context: ./php-fpm
    container_name: php-fpm
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${DATA_DIR}:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
    restart: always
    networks:
      - default
