version: "3"
services:
  nginx:
    image: iuxt/dnmp_nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
    volumes:
      - "${SOURCE_DIR}:/usr/share/nginx/html/:ro"
    environment:
      TZ: "${TZ}"
    restart: always
    networks:
      - default

  php:
    image: "iuxt/dnmp_php-fpm:${PHP_VERSION}"
    container_name: "php-fpm"
    expose:
      - 9000
    volumes:
      - "${SOURCE_DIR}:/usr/share/nginx/html/:rw"
    environment:
      TZ: "${TZ}"
    restart: always
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - "${MYSQL_DATA_DIR}:/var/lib/mysql/:rw"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: "${TZ}"
    restart: always
    networks:
      - default
