version: "3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:ro
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default

  php:
    build:
      context: ./php-fpm
    container_name: php-fpm
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
