version: "3"
services:
  nginx:
    build:
      context: ./service/nginx
    container_name: nginx
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
      - ${NGINX_HTTPS_HOST_PORT}:443
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:ro
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "${TZ}"
    restart: always
    networks:
      - default

  php:
    build:
      context: ./service/php-fpm_${PHP_VERSION}
    container_name: "php-fpm"
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html/:rw
      - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    environment:
      TZ: "${TZ}"
    restart: always
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "${TZ}"
    restart: always
    networks:
      - default
